### ISSUE TITLE
Synk fra marc2rdf til data.deichman.no er stoppet

### ISSUE THREAD

**Issue by asgeirr** [digibib/aktive-hyller#1]
data.deichman.no har ikke hatt tilvekst siden 14. november. Vi bør ha en måte å fange det opp når synk stopper og en metode for å få det i gang igjen som er dokumentert, slik at den kan utøres av flere

**Comment by bensinober** [comment]
det var nettverkstrøbbel ifbm. omlegging av nettverk.
fikset nå og satt igang ny sync. mulig det er for langt bak og at det beste er å lage ny kopi.

du kan sjekke synk mellom de to instansene ved å logge inn på data.deichman.no/conductor
og gå til Replication > Transactional > Subscriptions
så ser du siste transaksjonsnummer og status

tilsvarende på originalserver

![image](https://cloud.githubusercontent.com/assets/363338/5260254/b857f722-7a0c-11e4-8ad7-7e3a2d665d86.png)
